

# This file was *autogenerated* from the file ./attacks/ecm2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0)#!/bin/env sage

import sys
from sage.all import Integer

n = sys.argv[_sage_const_1 ]

def solve(n):
	n = Integer(n)
	primes = ecm.factor(n)
	return primes[_sage_const_0 ], primes[_sage_const_1 ]





